name: Build Dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    name: Build do projeto na branch dev

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar o .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar o projeto
        run: dotnet build --configuration Release --no-restore
